sudo: required
services:
  - docker

before_install:
  - docker build -t haitongye/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true haitongye/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Docker-React-Application"
  env: "Docker-React-Application-env"
  bucket_name: "elasticbeanstalk-us-east-1-028019069542"
  bucket_path: "Docker-React-Application"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"